modify vtrait internal method
JuliaAI/MLJModelInterface.jl pull request #126
Opened 2021-12-19 23:45 UTC by OkonSamuel

With respect to the removal of `TRAIT_FUNCTION_GIVEN_NAME`, `trait` function and `SET_CONVENTION` from [ScientificTypesBase.jl](https://github.com/JuliaAI/ScientificTypesBase.jl/pull/24). The following non-breaking changes have been made.
1. The Internal `vtrait` method has been slightly modified and no longer depends on `trait` method from `ScientificTypesBase`. This method now requires the `FullInterface` to run.
2. redefined `MODE` type as a `Union` type rather than an abstract type, to prevent users from extending this method, as that would affect performance ( so we take advantage of `julia`'s union splitting)
2. Code re-formatting (following Invenia [BlueStyle](https://github.com/invenia/BlueStyle)) and docstrings updates. (Well maybe this wasn't necessary)
3. The following data utils methods now require `FullInterface` mode in order to run otherwise they throw an `InterfaceError`. (This is non-breaking to developers as their code would still compile).
    a. `schema`
    b. `istable`
    c. `nrows`
    d. `selectrows`
    e. `selectcols`
    f. `select`

2021-12-20 00:46 UTC, ablaom commented on src/data_utils.jl
> +return the number of rows for a table, abstractvector or abtractmatrix, `X`.
I would either revert to the original or use "`AbstractVector`", "`AbstractMatrix`".

2021-12-20 01:18 UTC, ablaom reviewed
Thanks @OkonSamuel for the work here. Very much appreciated. 

Unfortunately, the extensive formatting changes make this very challenging to review, even with the nice overview, and I basically gave up, part way through. 

Be great if you can list all files with "real" changes, so I can be sure I've checked these. Since we are not releasing this as a breaking change, we need to be extra careful. 

It's also a little tricky to review without seeing the downstream changes in MLJBase re the light/full interface stuff, although we have discussed this offline. Please post your MLJBase PR already, tacitly assuming this PR is good. I'd like to do a complete local test of the rollout, including MLJModels, MLJTuning and a few 3rd party interfaces.

2021-12-20 08:02 UTC, OkonSamuel commented
> Thanks @OkonSamuel for the work here. Very much appreciated.
> 
> Unfortunately, the extensive formatting changes make this very challenging to review, even with the nice overview, and I basically gave up, part way through.
> 
> Be great if you can list all files with "real" changes, so I can be sure I've checked these. Since we are not releasing this as a breaking change, we need to be extra careful.
> 
> It's also a little tricky to review without seeing the downstream changes in MLJBase re the light/full interface stuff, although we have discussed this offline. Please post your MLJBase PR already, tacitly assuming this PR is good. I'd like to do a complete local test of the rollout, including MLJModels, MLJTuning and a few 3rd party interfaces.

Apologies. Here are the files containing actual changes, the remaining files just contain formatting changes.
1. src/MLJModelInterface.jl
2. src/data_utils.jl
3. test/data_utils.jl
4. test/mode.jl
5. test/runtests.jl

2021-12-21 03:38 UTC, ablaom commented on src/data_utils.jl
> +If `X isa AbstractMatrix`, return `X` or `permutedims(X)` if `transpose=true`.
good catch

2021-12-21 05:04 UTC, ablaom commented on src/data_utils.jl
> +return the number of rows for a table, abstractvector or abtractmatrix, `X`.
And `return` needs capitalisation.

2021-12-21 05:17 UTC, ablaom requested changes
Okay, I've reviewed the indicated files with real changes. 

Many thanks. Good to see the new tests for interface errors.

2021-12-21 20:42 UTC, ablaom approved these changes
Thanks!

2021-12-21 20:46 UTC, merged