Probabilisitic set
JuliaAI/MLJModelInterface.jl pull request #167
Opened 2022-11-04 09:48 UTC by pat-alt

Add the abstract type necessary to add conformal classifiers for general use (see [related issue](https://github.com/alan-turing-institute/MLJ.jl/issues/978)). Nothing done yet with respect to downstream tasks. Decided to use only `ProbabilisticSet` for now, as I'm not sure the other case is necessary. Also added the trait definition.

2022-11-06 23:05 UTC, ablaom commented on src/model_traits.jl
> +StatTraits.prediction_type(::Type{<:ProbabilisticSet}) = :probabistic_set
```suggestion
StatTraits.prediction_type(::Type{<:ProbabilisticSet}) = :probabilistic_set
```

2022-11-06 23:06 UTC, ablaom commented on src/model_traits.jl
> +StatTraits.prediction_type(::Type{<:ProbabilisticSet}) = :probabistic_set
```suggestion
StatTraits.prediction_type(::Type{<:ProbabilisticSet}) = :probabilistic_set
```

2022-11-06 23:07 UTC, ablaom requested changes
Looks, good thanks.

2022-11-24 23:08 UTC, ablaom commented
@pat-alt Perhaps you missed my suggestion above?

2022-11-24 23:54 UTC, merged

2022-11-25 11:32 UTC, pat-alt commented
> @pat-alt Perhaps you missed my suggestion above?

Indeed, I completely missed that, sorry! And thanks for doing, great to see this has now been merged. Thanks!